### ISSUE TITLE
FEATURE REQUEST: Forge Port?

### ISSUE THREAD

**Issue by alexhowell610** [Snownee/KubeJSEntityEventsExt#1]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

1.0.0

### Modloader version

Fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Basically title. I am creating bounties and challenges through Kubejs for my forge modpack and the kill counters are super inconsistent because there isn't something like the feature in this mod where it tells if you are directly responsible for killing another entity.

I don't want to be annoying asking for Forge but I have tried so many things to make it more consistent. Either way, I think this is a cool addon for Kubejs

**Comment by Snownee** [comment]
This mod is just a simple direct port of some events in Fabric API. There are no such counterparts in Forge. Therefore, there is no plan for the Forge port
